name: abs_tracker_f
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.4.10

  # State Management
  flutter_bloc: ^8.1.3
  provider: ^6.1.1

  # UI & Utils
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.0.7
  file_picker: ^10.3.7
  url_launcher: ^6.2.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true